### ISSUE TITLE
Change color

### ISSUE THREAD

**Issue by rightaway** [jonathantneal/postcss-svg#4]
I'm not using this for sprites, I just have an svg file that I'd like to inline but change its color when it gets inlined. Is this use case possible, how can it be done?

**Comment by rightaway** [comment]
I tried https://zslabs.com/articles/svg-background-fill/ but no matter what I set `fill` to the original fill value from the `.svg` file doesn't change in the rendered css.

**Comment by jonathantneal** [comment]
You could use SVG Parameters, which let you push compiled CSS variables into your SVGs.

Example: https://github.com/jonathantneal/postcss-svg#readme
